In [1]:
from load_mat_file import get_data
import numpy as np

In [2]:
x = get_data('market_attribute.mat')

In [3]:
x[1]

('age',
 'backpack',
 'bag',
 'handbag',
 'downblack',
 'downblue',
 'downbrown',
 'downgray',
 'downgreen',
 'downpink',
 'downpurple',
 'downwhite',
 'downyellow',
 'upblack',
 'upblue',
 'upgreen',
 'upgray',
 'uppurple',
 'upred',
 'upwhite',
 'upyellow',
 'clothes',
 'down',
 'up',
 'hair',
 'hat',
 'gender')

In [4]:
x[0].shape

(1501, 27)

In [5]:
for i in range(x[0].shape[0]):
        x[0][i] = x[0][i] - 1

In [6]:
for i in range(x[0].shape[0]):
    for j in range(4,13):
        if(x[0][i][j]==1):
            x[0][i][4] = j-4

In [7]:
for i in range(x[0].shape[0]):
    for j in range(13,21):
        if(x[0][i][j]==1):
            x[0][i][13] = j-13

In [8]:
x[0][0]

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0], dtype=uint8)

In [9]:
x[0][:,5] = x[0][:,13]

In [10]:
x[0][0]

array([1, 0, 1, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0], dtype=uint8)

In [11]:
x[0][:,6:12] = x[0][:,21:]

In [12]:
x[0][0]

array([1, 0, 1, 0, 0, 6, 1, 1, 1, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0], dtype=uint8)

In [13]:
y = x[0][:,:12]

In [14]:
labels = []

In [15]:
for i in x[1][:4]:
    labels.append(i)

In [16]:
labels

['age', 'backpack', 'bag', 'handbag']

In [17]:
labels.append('downcolor')
labels.append('upcolor')

In [18]:
for i in x[1][21:]:
    labels.append(i)

In [19]:
labels

['age',
 'backpack',
 'bag',
 'handbag',
 'downcolor',
 'upcolor',
 'clothes',
 'down',
 'up',
 'hair',
 'hat',
 'gender']

In [20]:
downcolor = []
for i in x[1][4:13]:
    downcolor.append(i)

In [21]:
upcolor = []
for i in x[1][13:21]:
    upcolor.append(i)

In [22]:
downcolor

['downblack',
 'downblue',
 'downbrown',
 'downgray',
 'downgreen',
 'downpink',
 'downpurple',
 'downwhite',
 'downyellow']

In [23]:
upcolor

['upblack',
 'upblue',
 'upgreen',
 'upgray',
 'uppurple',
 'upred',
 'upwhite',
 'upyellow']

In [24]:
np.save('attribute_data.npy',y)

In [25]:
np.save('labels.npy',labels)
np.save('downcolor.npy',downcolor)
np.save('upcolor.npy',upcolor)